[package]
name = "libappindicator"
version = "0.5.2"
description = "Rust safe bindings for libappindicator"
edition = "2018"
license = "MIT"
keywords = ["linux", "gui", "gtk"]

[dependencies]
log= "0.4"
glib= "0.14"
gtk= "0.14"
gtk-sys= "0.14"
libappindicator-sys = { version = "0.5", path = "sys/" }

